Document: cmorse
Title: Debian cmorse Manual
Author: <insert document author here>
Abstract: This manual describes what cmorse is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cmorse/cmorse.sgml.gz

Format: postscript
Files: /usr/share/doc/cmorse/cmorse.ps.gz

Format: text
Files: /usr/share/doc/cmorse/cmorse.text.gz

Format: HTML
Index: /usr/share/doc/cmorse/html/index.html
Files: /usr/share/doc/cmorse/html/*.html
